### ISSUE TITLE
Undefined fields

### ISSUE THREAD

**Issue by ma-rp** [jaw187/mlbprobablepitchers#2]
Hello,
Thank you very much for this initiative.

I'm running some simple examples as it's shown in the readme file but printing the json recursively to  see the inner objects and I'm getting some undefined fields.

For example:
const Probables = require('mlbprobablepitchers');
const day = '2016/05/03';
var util = require('util');
Probables.get(day, (err, matchups) => {
  console.log(util.inspect(matchups, false, null)); 
});

The response of this contains some empty ids and some fields as "undefined".

I'm pretty new with nodejs so I don't know if there's something wrong with the code that I'm running.

Thank you in advance for any help you could provide me!

**Comment by jaw187** [comment]
@ma-rp sorry for the delay ..... is this still in issue?
