### ISSUE TITLE
This isn't working

### ISSUE THREAD

**Issue by richardpenner** [jaw187/mlbprobablepitchers#3]
The tests fail, and the MLB API has clearly changed. I'd be happy to contribute a PR to make this work, but maybe this project is dead?

**Comment by jaw187** [comment]
always happy to accept PR.

**Comment by jaw187** [comment]
I took a quick run at it.  There is a new site that will require a new pattern for extracting the data.  Luckily it's still not in a nice json document, so the project has value :).

**Comment by richardpenner** [comment]
Yep, I happen to be working on a PR that changes the selectors and URL but is basically the same thing. If I can't get that to work this weekend, I might look into what the MLB At Bat app is doing, as it does show probable pitchers (and likely isn't scraping HTML…). If you have started on this too, please let me know and I'll hit the brakes.

**Comment by jaw187** [comment]
No, I haven't done much.  Keep going, you got this!!!

**Comment by jaw187** [comment]
Also interested in how you'd reverse engineer At Bat....

**Comment by richardpenner** [comment]
I would probably use `mitmproxy` to inspect the network traffic as I poke around the app.

**Comment by richardpenner** [comment]
Did it on my lunch break. Feedback welcome – I will have some time this afternoon.
