### ISSUE TITLE
startTime is undefined

### ISSUE THREAD

**Issue by richardpenner** [jaw187/mlbprobablepitchers#5]
Currently startTime and easternTime are undefined. I'll do another PR and add tests.

**Comment by richardpenner** [comment]
FYI I'm only seeing eastern time on this page. Thoughts on changing the contract to only provide the easternTimes key?

**Comment by ma-rp** [comment]
I think the overall response has changed:
-  the game id isn't part of the response anymore
- the teams now come by name instead of id

@jaw187 Is there any chance we can get that info back?
Thanks!

**Comment by richardpenner** [comment]
@ma-rp this project scrapes a website, which has changed (and will continue changing). I'm debating whether to start a new project that goes straight to the API, which might be more reliable. Any interest?

**Comment by richardpenner** [comment]
@ma-rp I made one that uses the javascript API, which does the job for me. feedback welcome: https://github.com/richardpenner/mlb-get-probable-pitchers
